FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build

WORKDIR /src

COPY WebApplication1/WebApplication1.csproj WebApplication1/
RUN dotnet restore WebApplication1/WebApplication1.csproj

COPY WebApplication1/ WebApplication1/

RUN dotnet publish WebApplication1/WebApplication1.csproj \
    -c Release \
    -o /app/publish \
    --no-restore


FROM mcr.microsoft.com/dotnet/aspnet:7.0

WORKDIR /app

COPY --from=build /app/publish .

ENV ASPNETCORE_URLS=http://0.0.0.0:80

CMD ["sh", "-c", "dotnet WebApplication1.dll --urls http://0.0.0.0:${PORT:-80}"]
