<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>c75bbec2-0a78-471c-82c4-1a32762e0fde</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.17.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="7.0.19" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
  </ItemGroup>

</Project>
